countdownSeconds: 0
startMessage: "â± La corsa inizia tra {seconds}..."
goMessage: "ğŸ GO!"
endMessage: "&aHai completato il percorso in {time}."
endChatMessage: "&aHai completato il percorso in {time}."
leaveSuccessMessage: ""
leaveNoActiveMessage: ""
maps: {}
